[2024-10-16T16:13:29.472+0000] {processor.py:153} INFO - Started process (PID=3044) to work on /opt/airflow/dags/sample.py
[2024-10-16T16:13:29.472+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sample.py for tasks to queue
[2024-10-16T16:13:29.473+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:13:29.473+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sample.py
[2024-10-16T16:13:29.552+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:13:29.550+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sample.py", line 3, in <module>
    from airflow.providers.mysql.hooks.mysql import MySQLHook
ImportError: cannot import name 'MySQLHook' from 'airflow.providers.mysql.hooks.mysql' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/mysql/hooks/mysql.py)
[2024-10-16T16:13:29.552+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sample.py
[2024-10-16T16:13:29.573+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sample.py took 0.104 seconds
[2024-10-16T16:13:59.864+0000] {processor.py:153} INFO - Started process (PID=3132) to work on /opt/airflow/dags/sample.py
[2024-10-16T16:13:59.866+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sample.py for tasks to queue
[2024-10-16T16:13:59.867+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:13:59.867+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sample.py
[2024-10-16T16:13:59.882+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:13:59.882+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sample.py", line 3, in <module>
    from airflow.providers.mysql.hooks.mysql import MySQLHook
ImportError: cannot import name 'MySQLHook' from 'airflow.providers.mysql.hooks.mysql' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/mysql/hooks/mysql.py)
[2024-10-16T16:13:59.883+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sample.py
[2024-10-16T16:13:59.901+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sample.py took 0.040 seconds
[2024-10-16T16:14:30.098+0000] {processor.py:153} INFO - Started process (PID=3244) to work on /opt/airflow/dags/sample.py
[2024-10-16T16:14:30.101+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sample.py for tasks to queue
[2024-10-16T16:14:30.101+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:14:30.101+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sample.py
[2024-10-16T16:14:30.118+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:14:30.117+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sample.py", line 3, in <module>
    from airflow.providers.mysql.hooks.mysql import MySQLHook
ImportError: cannot import name 'MySQLHook' from 'airflow.providers.mysql.hooks.mysql' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/mysql/hooks/mysql.py)
[2024-10-16T16:14:30.118+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sample.py
[2024-10-16T16:14:30.138+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sample.py took 0.043 seconds
[2024-10-16T16:15:00.254+0000] {processor.py:153} INFO - Started process (PID=3341) to work on /opt/airflow/dags/sample.py
[2024-10-16T16:15:00.256+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sample.py for tasks to queue
[2024-10-16T16:15:00.257+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:15:00.257+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sample.py
[2024-10-16T16:15:00.273+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:15:00.273+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sample.py", line 3, in <module>
    from airflow.providers.mysql.hooks.mysql import MySQLHook
ImportError: cannot import name 'MySQLHook' from 'airflow.providers.mysql.hooks.mysql' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/mysql/hooks/mysql.py)
[2024-10-16T16:15:00.274+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sample.py
[2024-10-16T16:15:00.302+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sample.py took 0.051 seconds
[2024-10-16T16:15:30.530+0000] {processor.py:153} INFO - Started process (PID=3444) to work on /opt/airflow/dags/sample.py
[2024-10-16T16:15:30.532+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sample.py for tasks to queue
[2024-10-16T16:15:30.533+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:15:30.533+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sample.py
[2024-10-16T16:15:30.546+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:15:30.546+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sample.py", line 3, in <module>
    from airflow.providers.mysql.hooks.mysql import MySQLHook
ImportError: cannot import name 'MySQLHook' from 'airflow.providers.mysql.hooks.mysql' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/mysql/hooks/mysql.py)
[2024-10-16T16:15:30.547+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sample.py
[2024-10-16T16:15:30.566+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sample.py took 0.039 seconds
[2024-10-16T16:16:00.687+0000] {processor.py:153} INFO - Started process (PID=3556) to work on /opt/airflow/dags/sample.py
[2024-10-16T16:16:00.689+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sample.py for tasks to queue
[2024-10-16T16:16:00.690+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:16:00.690+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sample.py
[2024-10-16T16:16:00.705+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:16:00.704+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sample.py", line 3, in <module>
    from airflow.providers.mysql.hooks.mysql import MySQLHook
ImportError: cannot import name 'MySQLHook' from 'airflow.providers.mysql.hooks.mysql' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/mysql/hooks/mysql.py)
[2024-10-16T16:16:00.705+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sample.py
[2024-10-16T16:16:00.724+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sample.py took 0.040 seconds
[2024-10-16T16:16:30.983+0000] {processor.py:153} INFO - Started process (PID=3645) to work on /opt/airflow/dags/sample.py
[2024-10-16T16:16:30.984+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sample.py for tasks to queue
[2024-10-16T16:16:30.985+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:16:30.985+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sample.py
[2024-10-16T16:16:31.000+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:16:30.999+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sample.py", line 3, in <module>
    from airflow.providers.mysql.hooks.mysql import MySQLHook
ImportError: cannot import name 'MySQLHook' from 'airflow.providers.mysql.hooks.mysql' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/mysql/hooks/mysql.py)
[2024-10-16T16:16:31.000+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sample.py
[2024-10-16T16:16:31.019+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sample.py took 0.038 seconds
[2024-10-16T16:17:01.202+0000] {processor.py:153} INFO - Started process (PID=3757) to work on /opt/airflow/dags/sample.py
[2024-10-16T16:17:01.205+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sample.py for tasks to queue
[2024-10-16T16:17:01.205+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:17:01.205+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sample.py
[2024-10-16T16:17:01.220+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:17:01.219+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sample.py", line 3, in <module>
    from airflow.providers.mysql.hooks.mysql import MySQLHook
ImportError: cannot import name 'MySQLHook' from 'airflow.providers.mysql.hooks.mysql' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/mysql/hooks/mysql.py)
[2024-10-16T16:17:01.220+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sample.py
[2024-10-16T16:17:01.239+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sample.py took 0.039 seconds
[2024-10-16T16:17:31.404+0000] {processor.py:153} INFO - Started process (PID=3845) to work on /opt/airflow/dags/sample.py
[2024-10-16T16:17:31.407+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sample.py for tasks to queue
[2024-10-16T16:17:31.407+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:17:31.407+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sample.py
[2024-10-16T16:17:31.424+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:17:31.423+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sample.py", line 3, in <module>
    from airflow.providers.mysql.hooks.mysql import MySQLHook
ImportError: cannot import name 'MySQLHook' from 'airflow.providers.mysql.hooks.mysql' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/mysql/hooks/mysql.py)
[2024-10-16T16:17:31.424+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sample.py
[2024-10-16T16:17:31.443+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sample.py took 0.042 seconds
[2024-10-16T16:18:01.737+0000] {processor.py:153} INFO - Started process (PID=3957) to work on /opt/airflow/dags/sample.py
[2024-10-16T16:18:01.740+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sample.py for tasks to queue
[2024-10-16T16:18:01.741+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:18:01.741+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sample.py
[2024-10-16T16:18:01.756+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:18:01.755+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sample.py", line 3, in <module>
    from airflow.providers.mysql.hooks.mysql import MySQLHook
ImportError: cannot import name 'MySQLHook' from 'airflow.providers.mysql.hooks.mysql' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/mysql/hooks/mysql.py)
[2024-10-16T16:18:01.756+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sample.py
[2024-10-16T16:18:01.776+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sample.py took 0.041 seconds
[2024-10-16T16:18:31.983+0000] {processor.py:153} INFO - Started process (PID=4069) to work on /opt/airflow/dags/sample.py
[2024-10-16T16:18:31.986+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sample.py for tasks to queue
[2024-10-16T16:18:31.988+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:18:31.988+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sample.py
[2024-10-16T16:18:32.008+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:18:32.007+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sample.py", line 3, in <module>
    from airflow.providers.mysql.hooks.mysql import MySQLHook
ImportError: cannot import name 'MySQLHook' from 'airflow.providers.mysql.hooks.mysql' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/mysql/hooks/mysql.py)
[2024-10-16T16:18:32.009+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sample.py
[2024-10-16T16:18:32.029+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sample.py took 0.049 seconds
[2024-10-16T16:19:02.107+0000] {processor.py:153} INFO - Started process (PID=4157) to work on /opt/airflow/dags/sample.py
[2024-10-16T16:19:02.110+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sample.py for tasks to queue
[2024-10-16T16:19:02.110+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:19:02.110+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sample.py
[2024-10-16T16:19:02.128+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:19:02.126+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sample.py", line 3, in <module>
    from airflow.providers.mysql.hooks.mysql import MySQLHook
ImportError: cannot import name 'MySQLHook' from 'airflow.providers.mysql.hooks.mysql' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/mysql/hooks/mysql.py)
[2024-10-16T16:19:02.129+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sample.py
[2024-10-16T16:19:02.152+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sample.py took 0.048 seconds
[2024-10-16T16:19:32.399+0000] {processor.py:153} INFO - Started process (PID=4270) to work on /opt/airflow/dags/sample.py
[2024-10-16T16:19:32.400+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sample.py for tasks to queue
[2024-10-16T16:19:32.401+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:19:32.401+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sample.py
[2024-10-16T16:19:32.416+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:19:32.416+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sample.py", line 3, in <module>
    from airflow.providers.mysql.hooks.mysql import MySQLHook
ImportError: cannot import name 'MySQLHook' from 'airflow.providers.mysql.hooks.mysql' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/mysql/hooks/mysql.py)
[2024-10-16T16:19:32.417+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sample.py
[2024-10-16T16:19:32.435+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sample.py took 0.039 seconds
[2024-10-16T16:20:02.750+0000] {processor.py:153} INFO - Started process (PID=4358) to work on /opt/airflow/dags/sample.py
[2024-10-16T16:20:02.752+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sample.py for tasks to queue
[2024-10-16T16:20:02.753+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:20:02.753+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sample.py
[2024-10-16T16:20:02.769+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:20:02.768+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sample.py", line 3, in <module>
    from airflow.providers.mysql.hooks.mysql import MySQLHook
ImportError: cannot import name 'MySQLHook' from 'airflow.providers.mysql.hooks.mysql' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/mysql/hooks/mysql.py)
[2024-10-16T16:20:02.769+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sample.py
[2024-10-16T16:20:02.790+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sample.py took 0.043 seconds
[2024-10-16T16:20:32.974+0000] {processor.py:153} INFO - Started process (PID=4470) to work on /opt/airflow/dags/sample.py
[2024-10-16T16:20:32.975+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sample.py for tasks to queue
[2024-10-16T16:20:32.976+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:20:32.976+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sample.py
[2024-10-16T16:20:32.990+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:20:32.989+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sample.py", line 3, in <module>
    from airflow.providers.mysql.hooks.mysql import MySQLHook
ImportError: cannot import name 'MySQLHook' from 'airflow.providers.mysql.hooks.mysql' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/mysql/hooks/mysql.py)
[2024-10-16T16:20:32.990+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sample.py
[2024-10-16T16:20:33.009+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sample.py took 0.038 seconds
[2024-10-16T16:21:03.181+0000] {processor.py:153} INFO - Started process (PID=4567) to work on /opt/airflow/dags/sample.py
[2024-10-16T16:21:03.183+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sample.py for tasks to queue
[2024-10-16T16:21:03.184+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:21:03.184+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sample.py
[2024-10-16T16:21:03.199+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:21:03.199+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sample.py", line 3, in <module>
    from airflow.providers.mysql.hooks.mysql import MySQLHook
ImportError: cannot import name 'MySQLHook' from 'airflow.providers.mysql.hooks.mysql' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/mysql/hooks/mysql.py)
[2024-10-16T16:21:03.200+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sample.py
[2024-10-16T16:21:03.220+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sample.py took 0.042 seconds
[2024-10-16T16:21:33.367+0000] {processor.py:153} INFO - Started process (PID=4671) to work on /opt/airflow/dags/sample.py
[2024-10-16T16:21:33.369+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sample.py for tasks to queue
[2024-10-16T16:21:33.370+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:21:33.370+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sample.py
[2024-10-16T16:21:33.384+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:21:33.384+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sample.py", line 3, in <module>
    from airflow.providers.mysql.hooks.mysql import MySQLHook
ImportError: cannot import name 'MySQLHook' from 'airflow.providers.mysql.hooks.mysql' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/mysql/hooks/mysql.py)
[2024-10-16T16:21:33.385+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sample.py
[2024-10-16T16:21:33.404+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sample.py took 0.040 seconds
[2024-10-16T16:22:03.608+0000] {processor.py:153} INFO - Started process (PID=4783) to work on /opt/airflow/dags/sample.py
[2024-10-16T16:22:03.610+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sample.py for tasks to queue
[2024-10-16T16:22:03.611+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:22:03.611+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sample.py
[2024-10-16T16:22:03.626+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:22:03.626+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sample.py", line 3, in <module>
    from airflow.providers.mysql.hooks.mysql import MySQLHook
ImportError: cannot import name 'MySQLHook' from 'airflow.providers.mysql.hooks.mysql' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/mysql/hooks/mysql.py)
[2024-10-16T16:22:03.627+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sample.py
[2024-10-16T16:22:03.646+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sample.py took 0.041 seconds
[2024-10-16T16:22:33.940+0000] {processor.py:153} INFO - Started process (PID=4871) to work on /opt/airflow/dags/sample.py
[2024-10-16T16:22:33.941+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sample.py for tasks to queue
[2024-10-16T16:22:33.942+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:22:33.942+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sample.py
[2024-10-16T16:22:33.957+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:22:33.956+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sample.py", line 3, in <module>
    from airflow.providers.mysql.hooks.mysql import MySQLHook
ImportError: cannot import name 'MySQLHook' from 'airflow.providers.mysql.hooks.mysql' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/mysql/hooks/mysql.py)
[2024-10-16T16:22:33.957+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sample.py
[2024-10-16T16:22:33.976+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sample.py took 0.039 seconds
[2024-10-16T16:23:04.135+0000] {processor.py:153} INFO - Started process (PID=4983) to work on /opt/airflow/dags/sample.py
[2024-10-16T16:23:04.136+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sample.py for tasks to queue
[2024-10-16T16:23:04.137+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:23:04.137+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sample.py
[2024-10-16T16:23:04.152+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:23:04.151+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sample.py", line 3, in <module>
    from airflow.providers.mysql.hooks.mysql import MySQLHook
ImportError: cannot import name 'MySQLHook' from 'airflow.providers.mysql.hooks.mysql' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/mysql/hooks/mysql.py)
[2024-10-16T16:23:04.152+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sample.py
[2024-10-16T16:23:04.171+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sample.py took 0.038 seconds
[2024-10-16T16:23:34.427+0000] {processor.py:153} INFO - Started process (PID=5078) to work on /opt/airflow/dags/sample.py
[2024-10-16T16:23:34.430+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sample.py for tasks to queue
[2024-10-16T16:23:34.430+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:23:34.430+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sample.py
[2024-10-16T16:23:34.446+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:23:34.445+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sample.py", line 3, in <module>
    from airflow.providers.mysql.hooks.mysql import MySQLHook
ImportError: cannot import name 'MySQLHook' from 'airflow.providers.mysql.hooks.mysql' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/mysql/hooks/mysql.py)
[2024-10-16T16:23:34.446+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sample.py
[2024-10-16T16:23:34.465+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sample.py took 0.041 seconds
[2024-10-16T16:24:04.589+0000] {processor.py:153} INFO - Started process (PID=5183) to work on /opt/airflow/dags/sample.py
[2024-10-16T16:24:04.591+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sample.py for tasks to queue
[2024-10-16T16:24:04.592+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:24:04.592+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sample.py
[2024-10-16T16:24:04.608+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:24:04.606+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sample.py", line 3, in <module>
    from airflow.providers.mysql.hooks.mysql import MySQLHook
ImportError: cannot import name 'MySQLHook' from 'airflow.providers.mysql.hooks.mysql' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/mysql/hooks/mysql.py)
[2024-10-16T16:24:04.608+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sample.py
[2024-10-16T16:24:04.627+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sample.py took 0.041 seconds
[2024-10-16T16:24:34.805+0000] {processor.py:153} INFO - Started process (PID=5295) to work on /opt/airflow/dags/sample.py
[2024-10-16T16:24:34.807+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sample.py for tasks to queue
[2024-10-16T16:24:34.807+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:24:34.807+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sample.py
[2024-10-16T16:24:34.823+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:24:34.823+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sample.py", line 3, in <module>
    from airflow.providers.mysql.hooks.mysql import MySQLHook
ImportError: cannot import name 'MySQLHook' from 'airflow.providers.mysql.hooks.mysql' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/mysql/hooks/mysql.py)
[2024-10-16T16:24:34.824+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sample.py
[2024-10-16T16:24:34.844+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sample.py took 0.041 seconds
[2024-10-16T16:25:04.959+0000] {processor.py:153} INFO - Started process (PID=5383) to work on /opt/airflow/dags/sample.py
[2024-10-16T16:25:04.962+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sample.py for tasks to queue
[2024-10-16T16:25:04.962+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:25:04.962+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sample.py
[2024-10-16T16:25:04.976+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:25:04.976+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sample.py", line 3, in <module>
    from airflow.providers.mysql.hooks.mysql import MySQLHook
ImportError: cannot import name 'MySQLHook' from 'airflow.providers.mysql.hooks.mysql' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/mysql/hooks/mysql.py)
[2024-10-16T16:25:04.976+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sample.py
[2024-10-16T16:25:04.995+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sample.py took 0.039 seconds
[2024-10-16T16:25:35.105+0000] {processor.py:153} INFO - Started process (PID=5496) to work on /opt/airflow/dags/sample.py
[2024-10-16T16:25:35.108+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sample.py for tasks to queue
[2024-10-16T16:25:35.108+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:25:35.108+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sample.py
[2024-10-16T16:25:35.124+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:25:35.123+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sample.py", line 3, in <module>
    from airflow.providers.mysql.hooks.mysql import MySQLHook
ImportError: cannot import name 'MySQLHook' from 'airflow.providers.mysql.hooks.mysql' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/mysql/hooks/mysql.py)
[2024-10-16T16:25:35.125+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sample.py
[2024-10-16T16:25:35.144+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sample.py took 0.041 seconds
[2024-10-16T16:26:05.302+0000] {processor.py:153} INFO - Started process (PID=5584) to work on /opt/airflow/dags/sample.py
[2024-10-16T16:26:05.305+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sample.py for tasks to queue
[2024-10-16T16:26:05.305+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:26:05.305+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sample.py
[2024-10-16T16:26:05.320+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:26:05.319+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sample.py", line 3, in <module>
    from airflow.providers.mysql.hooks.mysql import MySQLHook
ImportError: cannot import name 'MySQLHook' from 'airflow.providers.mysql.hooks.mysql' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/mysql/hooks/mysql.py)
[2024-10-16T16:26:05.320+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sample.py
[2024-10-16T16:26:05.339+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sample.py took 0.039 seconds
[2024-10-16T16:26:22.173+0000] {processor.py:153} INFO - Started process (PID=5663) to work on /opt/airflow/dags/sample.py
[2024-10-16T16:26:22.174+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sample.py for tasks to queue
[2024-10-16T16:26:22.175+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:26:22.174+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sample.py
[2024-10-16T16:26:22.192+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:26:22.191+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sample.py", line 3, in <module>
    from airflow.providers.mysql.hooks.mysql import MySQLHook
ImportError: cannot import name 'MySQLHook' from 'airflow.providers.mysql.hooks.mysql' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/mysql/hooks/mysql.py)
[2024-10-16T16:26:22.192+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sample.py
[2024-10-16T16:26:22.210+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sample.py took 0.040 seconds
[2024-10-16T16:26:38.723+0000] {processor.py:153} INFO - Started process (PID=5697) to work on /opt/airflow/dags/sample.py
[2024-10-16T16:26:38.724+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sample.py for tasks to queue
[2024-10-16T16:26:38.725+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:26:38.725+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sample.py
[2024-10-16T16:26:38.742+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:26:38.741+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sample.py", line 3, in <module>
    from airflow.providers.mysql.hooks.mysql import MySQLHook
ImportError: cannot import name 'MySQLHook' from 'airflow.providers.mysql.hooks.mysql' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/mysql/hooks/mysql.py)
[2024-10-16T16:26:38.742+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sample.py
[2024-10-16T16:26:38.760+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sample.py took 0.040 seconds
[2024-10-16T16:27:08.842+0000] {processor.py:153} INFO - Started process (PID=5809) to work on /opt/airflow/dags/sample.py
[2024-10-16T16:27:08.845+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sample.py for tasks to queue
[2024-10-16T16:27:08.845+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:27:08.845+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sample.py
[2024-10-16T16:27:08.861+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:27:08.860+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sample.py", line 3, in <module>
    from airflow.providers.mysql.hooks.mysql import MySQLHook
ImportError: cannot import name 'MySQLHook' from 'airflow.providers.mysql.hooks.mysql' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/mysql/hooks/mysql.py)
[2024-10-16T16:27:08.861+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sample.py
[2024-10-16T16:27:08.880+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sample.py took 0.041 seconds
[2024-10-16T16:27:38.961+0000] {processor.py:153} INFO - Started process (PID=5897) to work on /opt/airflow/dags/sample.py
[2024-10-16T16:27:38.963+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sample.py for tasks to queue
[2024-10-16T16:27:38.964+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:27:38.964+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sample.py
[2024-10-16T16:27:38.980+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:27:38.979+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sample.py", line 3, in <module>
    from airflow.providers.mysql.hooks.mysql import MySQLHook
ImportError: cannot import name 'MySQLHook' from 'airflow.providers.mysql.hooks.mysql' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/mysql/hooks/mysql.py)
[2024-10-16T16:27:38.980+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sample.py
[2024-10-16T16:27:39.000+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sample.py took 0.042 seconds
[2024-10-16T16:27:41.988+0000] {processor.py:153} INFO - Started process (PID=5907) to work on /opt/airflow/dags/sample.py
[2024-10-16T16:27:41.991+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sample.py for tasks to queue
[2024-10-16T16:27:41.992+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:27:41.991+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sample.py
[2024-10-16T16:27:42.008+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:27:42.007+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sample.py", line 3, in <module>
    from airflow.providers.mysql.hooks.mysql import MySQLHook
ImportError: cannot import name 'MySQLHook' from 'airflow.providers.mysql.hooks.mysql' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/mysql/hooks/mysql.py)
[2024-10-16T16:27:42.008+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sample.py
[2024-10-16T16:27:42.028+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sample.py took 0.043 seconds
[2024-10-16T16:28:12.112+0000] {processor.py:153} INFO - Started process (PID=6010) to work on /opt/airflow/dags/sample.py
[2024-10-16T16:28:12.114+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sample.py for tasks to queue
[2024-10-16T16:28:12.115+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:28:12.115+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sample.py
[2024-10-16T16:28:12.131+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:28:12.130+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sample.py", line 3, in <module>
    from airflow.providers.mysql.hooks.mysql import MySQLHook
ImportError: cannot import name 'MySQLHook' from 'airflow.providers.mysql.hooks.mysql' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/mysql/hooks/mysql.py)
[2024-10-16T16:28:12.131+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sample.py
[2024-10-16T16:28:12.151+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sample.py took 0.042 seconds
[2024-10-16T16:28:42.603+0000] {processor.py:153} INFO - Started process (PID=6122) to work on /opt/airflow/dags/sample.py
[2024-10-16T16:28:42.606+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sample.py for tasks to queue
[2024-10-16T16:28:42.607+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:28:42.607+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sample.py
[2024-10-16T16:28:42.622+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:28:42.622+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sample.py", line 3, in <module>
    from airflow.providers.mysql.hooks.mysql import MySQLHook
ImportError: cannot import name 'MySQLHook' from 'airflow.providers.mysql.hooks.mysql' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/mysql/hooks/mysql.py)
[2024-10-16T16:28:42.623+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sample.py
[2024-10-16T16:28:42.650+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sample.py took 0.050 seconds
[2024-10-16T16:29:12.760+0000] {processor.py:153} INFO - Started process (PID=6210) to work on /opt/airflow/dags/sample.py
[2024-10-16T16:29:12.763+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sample.py for tasks to queue
[2024-10-16T16:29:12.764+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:29:12.763+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sample.py
[2024-10-16T16:29:12.778+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:29:12.778+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sample.py", line 3, in <module>
    from airflow.providers.mysql.hooks.mysql import MySQLHook
ImportError: cannot import name 'MySQLHook' from 'airflow.providers.mysql.hooks.mysql' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/mysql/hooks/mysql.py)
[2024-10-16T16:29:12.778+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sample.py
[2024-10-16T16:29:12.798+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sample.py took 0.040 seconds
[2024-10-16T16:29:27.740+0000] {processor.py:153} INFO - Started process (PID=6289) to work on /opt/airflow/dags/sample.py
[2024-10-16T16:29:27.742+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sample.py for tasks to queue
[2024-10-16T16:29:27.742+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:29:27.742+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sample.py
[2024-10-16T16:29:27.759+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:29:27.758+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sample.py", line 3, in <module>
    from airflow.providers.mysql.hooks.mysql import MySQLHook
ImportError: cannot import name 'MySQLHook' from 'airflow.providers.mysql.hooks.mysql' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/mysql/hooks/mysql.py)
[2024-10-16T16:29:27.759+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sample.py
[2024-10-16T16:29:27.779+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sample.py took 0.041 seconds
[2024-10-16T16:29:58.039+0000] {processor.py:153} INFO - Started process (PID=6377) to work on /opt/airflow/dags/sample.py
[2024-10-16T16:29:58.041+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sample.py for tasks to queue
[2024-10-16T16:29:58.042+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:29:58.042+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sample.py
[2024-10-16T16:29:58.058+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:29:58.056+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sample.py", line 3, in <module>
    from airflow.providers.mysql.hooks.mysql import MySQLHook
ImportError: cannot import name 'MySQLHook' from 'airflow.providers.mysql.hooks.mysql' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/mysql/hooks/mysql.py)
[2024-10-16T16:29:58.058+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sample.py
[2024-10-16T16:29:58.078+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sample.py took 0.042 seconds
[2024-10-16T16:30:28.179+0000] {processor.py:153} INFO - Started process (PID=6489) to work on /opt/airflow/dags/sample.py
[2024-10-16T16:30:28.181+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sample.py for tasks to queue
[2024-10-16T16:30:28.182+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:30:28.181+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sample.py
[2024-10-16T16:30:28.197+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:30:28.196+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sample.py", line 3, in <module>
    from airflow.providers.mysql.hooks.mysql import MySQLHook
ImportError: cannot import name 'MySQLHook' from 'airflow.providers.mysql.hooks.mysql' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/mysql/hooks/mysql.py)
[2024-10-16T16:30:28.197+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sample.py
[2024-10-16T16:30:28.216+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sample.py took 0.039 seconds
[2024-10-16T16:30:58.327+0000] {processor.py:153} INFO - Started process (PID=6577) to work on /opt/airflow/dags/sample.py
[2024-10-16T16:30:58.329+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sample.py for tasks to queue
[2024-10-16T16:30:58.330+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:30:58.329+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sample.py
[2024-10-16T16:30:58.345+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:30:58.344+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sample.py", line 3, in <module>
    from airflow.providers.mysql.hooks.mysql import MySQLHook
ImportError: cannot import name 'MySQLHook' from 'airflow.providers.mysql.hooks.mysql' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/mysql/hooks/mysql.py)
[2024-10-16T16:30:58.345+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sample.py
[2024-10-16T16:30:58.365+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sample.py took 0.040 seconds
[2024-10-16T16:31:28.465+0000] {processor.py:153} INFO - Started process (PID=6689) to work on /opt/airflow/dags/sample.py
[2024-10-16T16:31:28.466+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sample.py for tasks to queue
[2024-10-16T16:31:28.467+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:31:28.467+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sample.py
[2024-10-16T16:31:28.481+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:31:28.481+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sample.py", line 3, in <module>
    from airflow.providers.mysql.hooks.mysql import MySQLHook
ImportError: cannot import name 'MySQLHook' from 'airflow.providers.mysql.hooks.mysql' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/mysql/hooks/mysql.py)
[2024-10-16T16:31:28.482+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sample.py
[2024-10-16T16:31:28.499+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sample.py took 0.037 seconds
[2024-10-16T16:31:58.927+0000] {processor.py:153} INFO - Started process (PID=6786) to work on /opt/airflow/dags/sample.py
[2024-10-16T16:31:58.928+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sample.py for tasks to queue
[2024-10-16T16:31:58.929+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:31:58.928+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sample.py
[2024-10-16T16:31:58.951+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:31:58.950+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sample.py", line 3, in <module>
    from airflow.providers.mysql.hooks.mysql import MySQLHook
ImportError: cannot import name 'MySQLHook' from 'airflow.providers.mysql.hooks.mysql' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/mysql/hooks/mysql.py)
[2024-10-16T16:31:58.952+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sample.py
[2024-10-16T16:31:58.971+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sample.py took 0.047 seconds
[2024-10-16T16:32:28.990+0000] {processor.py:153} INFO - Started process (PID=6889) to work on /opt/airflow/dags/sample.py
[2024-10-16T16:32:28.994+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sample.py for tasks to queue
[2024-10-16T16:32:28.994+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:32:28.994+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sample.py
[2024-10-16T16:32:29.022+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:32:29.021+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sample.py", line 3, in <module>
    from airflow.providers.mysql.hooks.mysql import MySQLHook
ImportError: cannot import name 'MySQLHook' from 'airflow.providers.mysql.hooks.mysql' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/mysql/hooks/mysql.py)
[2024-10-16T16:32:29.023+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sample.py
[2024-10-16T16:32:29.041+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sample.py took 0.054 seconds
[2024-10-16T16:32:59.116+0000] {processor.py:153} INFO - Started process (PID=7001) to work on /opt/airflow/dags/sample.py
[2024-10-16T16:32:59.117+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sample.py for tasks to queue
[2024-10-16T16:32:59.118+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:32:59.118+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sample.py
[2024-10-16T16:32:59.133+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:32:59.133+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sample.py", line 3, in <module>
    from airflow.providers.mysql.hooks.mysql import MySQLHook
ImportError: cannot import name 'MySQLHook' from 'airflow.providers.mysql.hooks.mysql' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/mysql/hooks/mysql.py)
[2024-10-16T16:32:59.134+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sample.py
[2024-10-16T16:32:59.151+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sample.py took 0.037 seconds
[2024-10-16T16:33:29.346+0000] {processor.py:153} INFO - Started process (PID=7088) to work on /opt/airflow/dags/sample.py
[2024-10-16T16:33:29.349+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sample.py for tasks to queue
[2024-10-16T16:33:29.350+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:33:29.350+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sample.py
[2024-10-16T16:33:29.365+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:33:29.364+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sample.py", line 3, in <module>
    from airflow.providers.mysql.hooks.mysql import MySQLHook
ImportError: cannot import name 'MySQLHook' from 'airflow.providers.mysql.hooks.mysql' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/mysql/hooks/mysql.py)
[2024-10-16T16:33:29.365+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sample.py
[2024-10-16T16:33:29.381+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sample.py took 0.037 seconds
[2024-10-16T16:33:59.447+0000] {processor.py:153} INFO - Started process (PID=7200) to work on /opt/airflow/dags/sample.py
[2024-10-16T16:33:59.450+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sample.py for tasks to queue
[2024-10-16T16:33:59.450+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:33:59.450+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sample.py
[2024-10-16T16:33:59.467+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:33:59.466+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sample.py", line 3, in <module>
    from airflow.providers.mysql.hooks.mysql import MySQLHook
ImportError: cannot import name 'MySQLHook' from 'airflow.providers.mysql.hooks.mysql' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/mysql/hooks/mysql.py)
[2024-10-16T16:33:59.467+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sample.py
[2024-10-16T16:33:59.485+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sample.py took 0.041 seconds
[2024-10-16T16:34:29.642+0000] {processor.py:153} INFO - Started process (PID=7287) to work on /opt/airflow/dags/sample.py
[2024-10-16T16:34:29.645+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sample.py for tasks to queue
[2024-10-16T16:34:29.645+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:34:29.645+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sample.py
[2024-10-16T16:34:29.661+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:34:29.660+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sample.py", line 3, in <module>
    from airflow.providers.mysql.hooks.mysql import MySQLHook
ImportError: cannot import name 'MySQLHook' from 'airflow.providers.mysql.hooks.mysql' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/mysql/hooks/mysql.py)
[2024-10-16T16:34:29.661+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sample.py
[2024-10-16T16:34:29.679+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sample.py took 0.040 seconds
[2024-10-16T16:34:59.824+0000] {processor.py:153} INFO - Started process (PID=7399) to work on /opt/airflow/dags/sample.py
[2024-10-16T16:34:59.827+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sample.py for tasks to queue
[2024-10-16T16:34:59.827+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:34:59.827+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sample.py
[2024-10-16T16:34:59.843+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:34:59.842+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sample.py", line 3, in <module>
    from airflow.providers.mysql.hooks.mysql import MySQLHook
ImportError: cannot import name 'MySQLHook' from 'airflow.providers.mysql.hooks.mysql' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/mysql/hooks/mysql.py)
[2024-10-16T16:34:59.843+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sample.py
[2024-10-16T16:34:59.862+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sample.py took 0.041 seconds
[2024-10-16T16:35:29.943+0000] {processor.py:153} INFO - Started process (PID=7496) to work on /opt/airflow/dags/sample.py
[2024-10-16T16:35:29.945+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sample.py for tasks to queue
[2024-10-16T16:35:29.946+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:35:29.946+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sample.py
[2024-10-16T16:35:29.961+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:35:29.960+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sample.py", line 3, in <module>
    from airflow.providers.mysql.hooks.mysql import MySQLHook
ImportError: cannot import name 'MySQLHook' from 'airflow.providers.mysql.hooks.mysql' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/mysql/hooks/mysql.py)
[2024-10-16T16:35:29.961+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sample.py
[2024-10-16T16:35:29.982+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sample.py took 0.042 seconds
[2024-10-16T16:36:00.065+0000] {processor.py:153} INFO - Started process (PID=7600) to work on /opt/airflow/dags/sample.py
[2024-10-16T16:36:00.068+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sample.py for tasks to queue
[2024-10-16T16:36:00.068+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:36:00.068+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sample.py
[2024-10-16T16:36:00.085+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:36:00.084+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sample.py", line 3, in <module>
    from airflow.providers.mysql.hooks.mysql import MySQLHook
ImportError: cannot import name 'MySQLHook' from 'airflow.providers.mysql.hooks.mysql' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/mysql/hooks/mysql.py)
[2024-10-16T16:36:00.085+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sample.py
[2024-10-16T16:36:00.103+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sample.py took 0.041 seconds
[2024-10-16T16:36:10.575+0000] {processor.py:153} INFO - Started process (PID=7634) to work on /opt/airflow/dags/sample.py
[2024-10-16T16:36:10.577+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sample.py for tasks to queue
[2024-10-16T16:36:10.577+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:36:10.577+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sample.py
[2024-10-16T16:36:10.579+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:36:10.578+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sample.py", line 17
    catchup=False) as dags:
                          ^
SyntaxError: unexpected EOF while parsing
[2024-10-16T16:36:10.579+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sample.py
[2024-10-16T16:36:10.599+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sample.py took 0.027 seconds
[2024-10-16T16:36:23.883+0000] {processor.py:153} INFO - Started process (PID=7682) to work on /opt/airflow/dags/sample.py
[2024-10-16T16:36:23.884+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sample.py for tasks to queue
[2024-10-16T16:36:23.885+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:36:23.885+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sample.py
[2024-10-16T16:36:23.888+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:36:23.886+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sample.py", line 25
    catchup=False) as dags:
                          ^
SyntaxError: unexpected EOF while parsing
[2024-10-16T16:36:23.888+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sample.py
[2024-10-16T16:36:23.913+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sample.py took 0.033 seconds
[2024-10-16T16:36:39.736+0000] {processor.py:153} INFO - Started process (PID=7723) to work on /opt/airflow/dags/sample.py
[2024-10-16T16:36:39.740+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sample.py for tasks to queue
[2024-10-16T16:36:39.741+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:36:39.740+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sample.py
[2024-10-16T16:36:39.742+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:36:39.742+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sample.py", line 27
    
    ^
SyntaxError: unexpected EOF while parsing
[2024-10-16T16:36:39.743+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sample.py
[2024-10-16T16:36:39.761+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sample.py took 0.028 seconds
[2024-10-16T16:36:56.308+0000] {processor.py:153} INFO - Started process (PID=7797) to work on /opt/airflow/dags/sample.py
[2024-10-16T16:36:56.309+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sample.py for tasks to queue
[2024-10-16T16:36:56.310+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:36:56.310+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sample.py
[2024-10-16T16:36:56.313+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:36:56.311+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sample.py", line 28
    
    ^
SyntaxError: unexpected EOF while parsing
[2024-10-16T16:36:56.313+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sample.py
[2024-10-16T16:36:56.334+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sample.py took 0.029 seconds
[2024-10-16T16:37:18.094+0000] {processor.py:153} INFO - Started process (PID=7860) to work on /opt/airflow/dags/sample.py
[2024-10-16T16:37:18.097+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sample.py for tasks to queue
[2024-10-16T16:37:18.098+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:37:18.098+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sample.py
[2024-10-16T16:37:18.105+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:37:18.103+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sample.py", line 28
    def scrapeplaystore_data()
                             ^
SyntaxError: invalid syntax
[2024-10-16T16:37:18.105+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sample.py
[2024-10-16T16:37:18.125+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sample.py took 0.034 seconds
[2024-10-16T16:37:44.234+0000] {processor.py:153} INFO - Started process (PID=7948) to work on /opt/airflow/dags/sample.py
[2024-10-16T16:37:44.235+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sample.py for tasks to queue
[2024-10-16T16:37:44.237+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:37:44.236+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sample.py
[2024-10-16T16:37:44.308+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:37:44.305+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sample.py", line 3, in <module>
    from airflow.providers.mysql.hooks.mysql import MySQLHook
ImportError: cannot import name 'MySQLHook' from 'airflow.providers.mysql.hooks.mysql' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/mysql/hooks/mysql.py)
[2024-10-16T16:37:44.308+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sample.py
[2024-10-16T16:37:44.368+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sample.py took 0.139 seconds
[2024-10-16T16:38:14.419+0000] {processor.py:153} INFO - Started process (PID=8036) to work on /opt/airflow/dags/sample.py
[2024-10-16T16:38:14.423+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sample.py for tasks to queue
[2024-10-16T16:38:14.423+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:38:14.423+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sample.py
[2024-10-16T16:38:14.455+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:38:14.453+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sample.py", line 3, in <module>
    from airflow.providers.mysql.hooks.mysql import MySQLHook
ImportError: cannot import name 'MySQLHook' from 'airflow.providers.mysql.hooks.mysql' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/mysql/hooks/mysql.py)
[2024-10-16T16:38:14.455+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sample.py
[2024-10-16T16:38:14.471+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sample.py took 0.054 seconds
[2024-10-16T16:38:44.524+0000] {processor.py:153} INFO - Started process (PID=8148) to work on /opt/airflow/dags/sample.py
[2024-10-16T16:38:44.527+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sample.py for tasks to queue
[2024-10-16T16:38:44.527+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:38:44.527+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sample.py
[2024-10-16T16:38:44.542+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:38:44.542+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sample.py", line 3, in <module>
    from airflow.providers.mysql.hooks.mysql import MySQLHook
ImportError: cannot import name 'MySQLHook' from 'airflow.providers.mysql.hooks.mysql' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/mysql/hooks/mysql.py)
[2024-10-16T16:38:44.543+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sample.py
[2024-10-16T16:38:44.562+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sample.py took 0.040 seconds
[2024-10-16T16:39:14.666+0000] {processor.py:153} INFO - Started process (PID=8236) to work on /opt/airflow/dags/sample.py
[2024-10-16T16:39:14.667+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sample.py for tasks to queue
[2024-10-16T16:39:14.667+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:39:14.667+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sample.py
[2024-10-16T16:39:14.683+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:39:14.682+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sample.py", line 3, in <module>
    from airflow.providers.mysql.hooks.mysql import MySQLHook
ImportError: cannot import name 'MySQLHook' from 'airflow.providers.mysql.hooks.mysql' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/mysql/hooks/mysql.py)
[2024-10-16T16:39:14.683+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sample.py
[2024-10-16T16:39:14.702+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sample.py took 0.039 seconds
[2024-10-16T16:39:44.818+0000] {processor.py:153} INFO - Started process (PID=8348) to work on /opt/airflow/dags/sample.py
[2024-10-16T16:39:44.819+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sample.py for tasks to queue
[2024-10-16T16:39:44.820+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:39:44.820+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sample.py
[2024-10-16T16:39:44.841+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:39:44.840+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sample.py", line 3, in <module>
    from airflow.providers.mysql.hooks.mysql import MySQLHook
ImportError: cannot import name 'MySQLHook' from 'airflow.providers.mysql.hooks.mysql' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/mysql/hooks/mysql.py)
[2024-10-16T16:39:44.841+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sample.py
[2024-10-16T16:39:44.860+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sample.py took 0.045 seconds
[2024-10-16T16:40:03.673+0000] {processor.py:153} INFO - Started process (PID=8403) to work on /opt/airflow/dags/sample.py
[2024-10-16T16:40:03.675+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sample.py for tasks to queue
[2024-10-16T16:40:03.676+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:40:03.676+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sample.py
[2024-10-16T16:40:03.694+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:40:03.693+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sample.py", line 3, in <module>
    from airflow.providers.mysql.hooks.mysql import MySQLHook
ImportError: cannot import name 'MySQLHook' from 'airflow.providers.mysql.hooks.mysql' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/mysql/hooks/mysql.py)
[2024-10-16T16:40:03.695+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sample.py
[2024-10-16T16:40:03.715+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sample.py took 0.045 seconds
[2024-10-16T16:40:24.114+0000] {processor.py:153} INFO - Started process (PID=8477) to work on /opt/airflow/dags/sample.py
[2024-10-16T16:40:24.116+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sample.py for tasks to queue
[2024-10-16T16:40:24.117+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:40:24.117+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sample.py
[2024-10-16T16:40:24.149+0000] {processor.py:753} INFO - DAG(s) dict_keys(['weather_etl_pipeline']) retrieved from /opt/airflow/dags/sample.py
[2024-10-16T16:40:24.304+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:40:24.304+0000] {manager.py:504} INFO - Created Permission View: can edit on DAG:weather_etl_pipeline
[2024-10-16T16:40:24.314+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:40:24.314+0000] {manager.py:504} INFO - Created Permission View: can delete on DAG:weather_etl_pipeline
[2024-10-16T16:40:24.321+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:40:24.321+0000] {manager.py:504} INFO - Created Permission View: can read on DAG:weather_etl_pipeline
[2024-10-16T16:40:24.321+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:40:24.321+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-10-16T16:40:24.334+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:40:24.334+0000] {dag.py:2711} INFO - Creating ORM DAG for weather_etl_pipeline
[2024-10-16T16:40:24.344+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:40:24.344+0000] {dag.py:3441} INFO - Setting next_dagrun for weather_etl_pipeline to 2024-10-15T00:00:00+00:00, run_after=2024-10-16T00:00:00+00:00
[2024-10-16T16:40:24.360+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sample.py took 0.250 seconds
[2024-10-16T16:40:44.308+0000] {processor.py:153} INFO - Started process (PID=8548) to work on /opt/airflow/dags/sample.py
[2024-10-16T16:40:44.309+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sample.py for tasks to queue
[2024-10-16T16:40:44.309+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:40:44.309+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sample.py
[2024-10-16T16:40:44.342+0000] {processor.py:753} INFO - DAG(s) dict_keys(['weather_etl_pipeline']) retrieved from /opt/airflow/dags/sample.py
[2024-10-16T16:40:44.354+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:40:44.354+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-10-16T16:40:44.376+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:40:44.376+0000] {dag.py:3441} INFO - Setting next_dagrun for weather_etl_pipeline to 2024-10-15T00:00:00+00:00, run_after=2024-10-16T00:00:00+00:00
[2024-10-16T16:40:44.394+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sample.py took 0.090 seconds
[2024-10-16T16:41:14.610+0000] {processor.py:153} INFO - Started process (PID=8637) to work on /opt/airflow/dags/sample.py
[2024-10-16T16:41:14.612+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sample.py for tasks to queue
[2024-10-16T16:41:14.612+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:41:14.612+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sample.py
[2024-10-16T16:41:14.645+0000] {processor.py:753} INFO - DAG(s) dict_keys(['weather_etl_pipeline']) retrieved from /opt/airflow/dags/sample.py
[2024-10-16T16:41:14.663+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:41:14.663+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-10-16T16:41:14.683+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:41:14.683+0000] {dag.py:3441} INFO - Setting next_dagrun for weather_etl_pipeline to 2024-10-15T00:00:00+00:00, run_after=2024-10-16T00:00:00+00:00
[2024-10-16T16:41:14.703+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sample.py took 0.096 seconds
[2024-10-16T16:41:44.757+0000] {processor.py:153} INFO - Started process (PID=8749) to work on /opt/airflow/dags/sample.py
[2024-10-16T16:41:44.758+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sample.py for tasks to queue
[2024-10-16T16:41:44.759+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:41:44.759+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sample.py
[2024-10-16T16:41:44.791+0000] {processor.py:753} INFO - DAG(s) dict_keys(['weather_etl_pipeline']) retrieved from /opt/airflow/dags/sample.py
[2024-10-16T16:41:44.811+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:41:44.810+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-10-16T16:41:44.833+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:41:44.833+0000] {dag.py:3441} INFO - Setting next_dagrun for weather_etl_pipeline to 2024-10-15T00:00:00+00:00, run_after=2024-10-16T00:00:00+00:00
[2024-10-16T16:41:44.851+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sample.py took 0.097 seconds
[2024-10-16T16:42:15.221+0000] {processor.py:153} INFO - Started process (PID=8846) to work on /opt/airflow/dags/sample.py
[2024-10-16T16:42:15.223+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sample.py for tasks to queue
[2024-10-16T16:42:15.224+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:42:15.223+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sample.py
[2024-10-16T16:42:15.253+0000] {processor.py:753} INFO - DAG(s) dict_keys(['weather_etl_pipeline']) retrieved from /opt/airflow/dags/sample.py
[2024-10-16T16:42:15.273+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:42:15.273+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-10-16T16:42:15.295+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:42:15.295+0000] {dag.py:3441} INFO - Setting next_dagrun for weather_etl_pipeline to 2024-10-15T00:00:00+00:00, run_after=2024-10-16T00:00:00+00:00
[2024-10-16T16:42:15.317+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sample.py took 0.098 seconds
[2024-10-16T16:42:45.668+0000] {processor.py:153} INFO - Started process (PID=8949) to work on /opt/airflow/dags/sample.py
[2024-10-16T16:42:45.669+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sample.py for tasks to queue
[2024-10-16T16:42:45.670+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:42:45.670+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sample.py
[2024-10-16T16:42:45.711+0000] {processor.py:753} INFO - DAG(s) dict_keys(['weather_etl_pipeline']) retrieved from /opt/airflow/dags/sample.py
[2024-10-16T16:42:45.746+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:42:45.746+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-10-16T16:42:45.781+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:42:45.781+0000] {dag.py:3441} INFO - Setting next_dagrun for weather_etl_pipeline to 2024-10-15T00:00:00+00:00, run_after=2024-10-16T00:00:00+00:00
[2024-10-16T16:42:45.809+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sample.py took 0.145 seconds
[2024-10-16T16:43:15.928+0000] {processor.py:153} INFO - Started process (PID=9061) to work on /opt/airflow/dags/sample.py
[2024-10-16T16:43:15.931+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sample.py for tasks to queue
[2024-10-16T16:43:15.931+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:43:15.931+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sample.py
[2024-10-16T16:43:15.965+0000] {processor.py:753} INFO - DAG(s) dict_keys(['weather_etl_pipeline']) retrieved from /opt/airflow/dags/sample.py
[2024-10-16T16:43:15.982+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:43:15.982+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-10-16T16:43:16.003+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:43:16.003+0000] {dag.py:3441} INFO - Setting next_dagrun for weather_etl_pipeline to 2024-10-15T00:00:00+00:00, run_after=2024-10-16T00:00:00+00:00
[2024-10-16T16:43:16.023+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sample.py took 0.097 seconds
[2024-10-16T16:43:46.280+0000] {processor.py:153} INFO - Started process (PID=9149) to work on /opt/airflow/dags/sample.py
[2024-10-16T16:43:46.282+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sample.py for tasks to queue
[2024-10-16T16:43:46.283+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:43:46.283+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sample.py
[2024-10-16T16:43:46.314+0000] {processor.py:753} INFO - DAG(s) dict_keys(['weather_etl_pipeline']) retrieved from /opt/airflow/dags/sample.py
[2024-10-16T16:43:46.334+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:43:46.334+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-10-16T16:43:46.358+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:43:46.358+0000] {dag.py:3441} INFO - Setting next_dagrun for weather_etl_pipeline to 2024-10-15T00:00:00+00:00, run_after=2024-10-16T00:00:00+00:00
[2024-10-16T16:43:46.376+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sample.py took 0.099 seconds
[2024-10-16T16:43:59.863+0000] {processor.py:153} INFO - Started process (PID=9199) to work on /opt/airflow/dags/sample.py
[2024-10-16T16:43:59.864+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sample.py for tasks to queue
[2024-10-16T16:43:59.865+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:43:59.865+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sample.py
[2024-10-16T16:43:59.894+0000] {processor.py:753} INFO - DAG(s) dict_keys(['weather_etl_pipeline']) retrieved from /opt/airflow/dags/sample.py
[2024-10-16T16:43:59.913+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:43:59.913+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-10-16T16:43:59.933+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:43:59.933+0000] {dag.py:3441} INFO - Setting next_dagrun for weather_etl_pipeline to 2024-10-15T00:00:00+00:00, run_after=2024-10-16T00:00:00+00:00
[2024-10-16T16:43:59.953+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sample.py took 0.093 seconds
[2024-10-16T16:44:07.445+0000] {processor.py:153} INFO - Started process (PID=9233) to work on /opt/airflow/dags/sample.py
[2024-10-16T16:44:07.446+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sample.py for tasks to queue
[2024-10-16T16:44:07.447+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:44:07.447+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sample.py
[2024-10-16T16:44:07.449+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:44:07.448+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sample.py", line 35
    cursor.execute("""
                       )
                      
                       ^
SyntaxError: EOF while scanning triple-quoted string literal
[2024-10-16T16:44:07.449+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/sample.py
[2024-10-16T16:44:07.469+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sample.py took 0.026 seconds
[2024-10-16T16:44:14.574+0000] {processor.py:153} INFO - Started process (PID=9263) to work on /opt/airflow/dags/sample.py
[2024-10-16T16:44:14.575+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sample.py for tasks to queue
[2024-10-16T16:44:14.576+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:44:14.575+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sample.py
[2024-10-16T16:44:14.608+0000] {processor.py:753} INFO - DAG(s) dict_keys(['weather_etl_pipeline']) retrieved from /opt/airflow/dags/sample.py
[2024-10-16T16:44:14.629+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:44:14.629+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-10-16T16:44:14.650+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:44:14.650+0000] {dag.py:3441} INFO - Setting next_dagrun for weather_etl_pipeline to 2024-10-15T00:00:00+00:00, run_after=2024-10-16T00:00:00+00:00
[2024-10-16T16:44:14.677+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sample.py took 0.106 seconds
[2024-10-16T16:44:28.175+0000] {processor.py:153} INFO - Started process (PID=9311) to work on /opt/airflow/dags/sample.py
[2024-10-16T16:44:28.176+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sample.py for tasks to queue
[2024-10-16T16:44:28.177+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:44:28.177+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sample.py
[2024-10-16T16:44:28.208+0000] {processor.py:753} INFO - DAG(s) dict_keys(['weather_etl_pipeline']) retrieved from /opt/airflow/dags/sample.py
[2024-10-16T16:44:28.226+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:44:28.226+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-10-16T16:44:28.245+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:44:28.245+0000] {dag.py:3441} INFO - Setting next_dagrun for weather_etl_pipeline to 2024-10-15T00:00:00+00:00, run_after=2024-10-16T00:00:00+00:00
[2024-10-16T16:44:28.263+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sample.py took 0.092 seconds
[2024-10-16T16:44:58.320+0000] {processor.py:153} INFO - Started process (PID=9399) to work on /opt/airflow/dags/sample.py
[2024-10-16T16:44:58.322+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sample.py for tasks to queue
[2024-10-16T16:44:58.322+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:44:58.322+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sample.py
[2024-10-16T16:44:58.354+0000] {processor.py:753} INFO - DAG(s) dict_keys(['weather_etl_pipeline']) retrieved from /opt/airflow/dags/sample.py
[2024-10-16T16:44:58.372+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:44:58.371+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-10-16T16:44:58.391+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:44:58.391+0000] {dag.py:3441} INFO - Setting next_dagrun for weather_etl_pipeline to 2024-10-15T00:00:00+00:00, run_after=2024-10-16T00:00:00+00:00
[2024-10-16T16:44:58.412+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sample.py took 0.094 seconds
[2024-10-16T16:45:02.723+0000] {processor.py:153} INFO - Started process (PID=9431) to work on /opt/airflow/dags/sample.py
[2024-10-16T16:45:02.726+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sample.py for tasks to queue
[2024-10-16T16:45:02.726+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:45:02.726+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sample.py
[2024-10-16T16:45:02.758+0000] {processor.py:753} INFO - DAG(s) dict_keys(['weather_etl_pipeline']) retrieved from /opt/airflow/dags/sample.py
[2024-10-16T16:45:02.777+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:45:02.777+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-10-16T16:45:02.796+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:45:02.795+0000] {dag.py:3441} INFO - Setting next_dagrun for weather_etl_pipeline to 2024-10-15T00:00:00+00:00, run_after=2024-10-16T00:00:00+00:00
[2024-10-16T16:45:02.817+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sample.py took 0.097 seconds
[2024-10-16T16:45:32.984+0000] {processor.py:153} INFO - Started process (PID=9519) to work on /opt/airflow/dags/sample.py
[2024-10-16T16:45:32.987+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sample.py for tasks to queue
[2024-10-16T16:45:32.988+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:45:32.987+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sample.py
[2024-10-16T16:45:33.019+0000] {processor.py:753} INFO - DAG(s) dict_keys(['weather_etl_pipeline']) retrieved from /opt/airflow/dags/sample.py
[2024-10-16T16:45:33.038+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:45:33.038+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-10-16T16:45:33.058+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:45:33.058+0000] {dag.py:3441} INFO - Setting next_dagrun for weather_etl_pipeline to 2024-10-15T00:00:00+00:00, run_after=2024-10-16T00:00:00+00:00
[2024-10-16T16:45:33.075+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sample.py took 0.094 seconds
[2024-10-16T16:46:03.334+0000] {processor.py:153} INFO - Started process (PID=9631) to work on /opt/airflow/dags/sample.py
[2024-10-16T16:46:03.336+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sample.py for tasks to queue
[2024-10-16T16:46:03.336+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:46:03.336+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sample.py
[2024-10-16T16:46:03.375+0000] {processor.py:753} INFO - DAG(s) dict_keys(['weather_etl_pipeline']) retrieved from /opt/airflow/dags/sample.py
[2024-10-16T16:46:03.398+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:46:03.397+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-10-16T16:46:03.422+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:46:03.422+0000] {dag.py:3441} INFO - Setting next_dagrun for weather_etl_pipeline to 2024-10-15T00:00:00+00:00, run_after=2024-10-16T00:00:00+00:00
[2024-10-16T16:46:03.439+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sample.py took 0.108 seconds
[2024-10-16T16:46:07.442+0000] {processor.py:153} INFO - Started process (PID=9632) to work on /opt/airflow/dags/sample.py
[2024-10-16T16:46:07.443+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sample.py for tasks to queue
[2024-10-16T16:46:07.444+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:46:07.444+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sample.py
[2024-10-16T16:46:07.475+0000] {processor.py:753} INFO - DAG(s) dict_keys(['weather_etl_pipeline']) retrieved from /opt/airflow/dags/sample.py
[2024-10-16T16:46:07.494+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:46:07.494+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-10-16T16:46:07.515+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:46:07.515+0000] {dag.py:3441} INFO - Setting next_dagrun for weather_etl_pipeline to 2024-10-15T00:00:00+00:00, run_after=2024-10-16T00:00:00+00:00
[2024-10-16T16:46:07.537+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sample.py took 0.097 seconds
[2024-10-16T16:46:37.629+0000] {processor.py:153} INFO - Started process (PID=9745) to work on /opt/airflow/dags/sample.py
[2024-10-16T16:46:37.632+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sample.py for tasks to queue
[2024-10-16T16:46:37.632+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:46:37.632+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sample.py
[2024-10-16T16:46:37.663+0000] {processor.py:753} INFO - DAG(s) dict_keys(['weather_etl_pipeline']) retrieved from /opt/airflow/dags/sample.py
[2024-10-16T16:46:37.679+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:46:37.679+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-10-16T16:46:37.699+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:46:37.699+0000] {dag.py:3441} INFO - Setting next_dagrun for weather_etl_pipeline to 2024-10-15T00:00:00+00:00, run_after=2024-10-16T00:00:00+00:00
[2024-10-16T16:46:37.717+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sample.py took 0.091 seconds
[2024-10-16T16:47:07.897+0000] {processor.py:153} INFO - Started process (PID=9832) to work on /opt/airflow/dags/sample.py
[2024-10-16T16:47:07.898+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sample.py for tasks to queue
[2024-10-16T16:47:07.899+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:47:07.899+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sample.py
[2024-10-16T16:47:07.934+0000] {processor.py:753} INFO - DAG(s) dict_keys(['weather_etl_pipeline']) retrieved from /opt/airflow/dags/sample.py
[2024-10-16T16:47:07.951+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:47:07.951+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-10-16T16:47:07.973+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:47:07.973+0000] {dag.py:3441} INFO - Setting next_dagrun for weather_etl_pipeline to 2024-10-15T00:00:00+00:00, run_after=2024-10-16T00:00:00+00:00
[2024-10-16T16:47:07.991+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sample.py took 0.097 seconds
[2024-10-16T16:47:38.161+0000] {processor.py:153} INFO - Started process (PID=9944) to work on /opt/airflow/dags/sample.py
[2024-10-16T16:47:38.162+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sample.py for tasks to queue
[2024-10-16T16:47:38.163+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:47:38.163+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sample.py
[2024-10-16T16:47:38.193+0000] {processor.py:753} INFO - DAG(s) dict_keys(['weather_etl_pipeline']) retrieved from /opt/airflow/dags/sample.py
[2024-10-16T16:47:38.212+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:47:38.212+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-10-16T16:47:38.232+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:47:38.231+0000] {dag.py:3441} INFO - Setting next_dagrun for weather_etl_pipeline to 2024-10-15T00:00:00+00:00, run_after=2024-10-16T00:00:00+00:00
[2024-10-16T16:47:38.250+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sample.py took 0.092 seconds
[2024-10-16T16:48:08.363+0000] {processor.py:153} INFO - Started process (PID=10055) to work on /opt/airflow/dags/sample.py
[2024-10-16T16:48:08.365+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sample.py for tasks to queue
[2024-10-16T16:48:08.365+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:48:08.365+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sample.py
[2024-10-16T16:48:08.403+0000] {processor.py:753} INFO - DAG(s) dict_keys(['weather_etl_pipeline']) retrieved from /opt/airflow/dags/sample.py
[2024-10-16T16:48:08.426+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:48:08.425+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-10-16T16:48:08.447+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:48:08.447+0000] {dag.py:3441} INFO - Setting next_dagrun for weather_etl_pipeline to 2024-10-15T00:00:00+00:00, run_after=2024-10-16T00:00:00+00:00
[2024-10-16T16:48:08.463+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sample.py took 0.104 seconds
[2024-10-16T16:48:38.541+0000] {processor.py:153} INFO - Started process (PID=10143) to work on /opt/airflow/dags/sample.py
[2024-10-16T16:48:38.542+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sample.py for tasks to queue
[2024-10-16T16:48:38.543+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:48:38.543+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sample.py
[2024-10-16T16:48:38.573+0000] {processor.py:753} INFO - DAG(s) dict_keys(['weather_etl_pipeline']) retrieved from /opt/airflow/dags/sample.py
[2024-10-16T16:48:38.592+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:48:38.591+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-10-16T16:48:38.610+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:48:38.610+0000] {dag.py:3441} INFO - Setting next_dagrun for weather_etl_pipeline to 2024-10-15T00:00:00+00:00, run_after=2024-10-16T00:00:00+00:00
[2024-10-16T16:48:38.630+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sample.py took 0.092 seconds
[2024-10-16T16:49:06.733+0000] {processor.py:153} INFO - Started process (PID=10255) to work on /opt/airflow/dags/sample.py
[2024-10-16T16:49:06.734+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sample.py for tasks to queue
[2024-10-16T16:49:06.735+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:49:06.735+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sample.py
[2024-10-16T16:49:06.770+0000] {processor.py:753} INFO - DAG(s) dict_keys(['weather_etl_pipeline']) retrieved from /opt/airflow/dags/sample.py
[2024-10-16T16:49:06.789+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:49:06.788+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-10-16T16:49:06.811+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:49:06.811+0000] {dag.py:3441} INFO - Setting next_dagrun for weather_etl_pipeline to 2024-10-15T00:00:00+00:00, run_after=2024-10-16T00:00:00+00:00
[2024-10-16T16:49:06.829+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sample.py took 0.099 seconds
[2024-10-16T16:49:36.946+0000] {processor.py:153} INFO - Started process (PID=10343) to work on /opt/airflow/dags/sample.py
[2024-10-16T16:49:36.949+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sample.py for tasks to queue
[2024-10-16T16:49:36.949+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:49:36.949+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sample.py
[2024-10-16T16:49:37.000+0000] {processor.py:753} INFO - DAG(s) dict_keys(['weather_etl_pipeline']) retrieved from /opt/airflow/dags/sample.py
[2024-10-16T16:49:37.021+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:49:37.021+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-10-16T16:49:37.041+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:49:37.041+0000] {dag.py:3441} INFO - Setting next_dagrun for weather_etl_pipeline to 2024-10-15T00:00:00+00:00, run_after=2024-10-16T00:00:00+00:00
[2024-10-16T16:49:37.057+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sample.py took 0.113 seconds
[2024-10-16T16:50:07.139+0000] {processor.py:153} INFO - Started process (PID=10455) to work on /opt/airflow/dags/sample.py
[2024-10-16T16:50:07.141+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sample.py for tasks to queue
[2024-10-16T16:50:07.142+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:50:07.142+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sample.py
[2024-10-16T16:50:07.172+0000] {processor.py:753} INFO - DAG(s) dict_keys(['weather_etl_pipeline']) retrieved from /opt/airflow/dags/sample.py
[2024-10-16T16:50:07.190+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:50:07.190+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-10-16T16:50:07.215+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:50:07.215+0000] {dag.py:3441} INFO - Setting next_dagrun for weather_etl_pipeline to 2024-10-15T00:00:00+00:00, run_after=2024-10-16T00:00:00+00:00
[2024-10-16T16:50:07.240+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sample.py took 0.104 seconds
[2024-10-16T16:50:37.319+0000] {processor.py:153} INFO - Started process (PID=10543) to work on /opt/airflow/dags/sample.py
[2024-10-16T16:50:37.321+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sample.py for tasks to queue
[2024-10-16T16:50:37.322+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:50:37.321+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sample.py
[2024-10-16T16:50:37.350+0000] {processor.py:753} INFO - DAG(s) dict_keys(['weather_etl_pipeline']) retrieved from /opt/airflow/dags/sample.py
[2024-10-16T16:50:37.368+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:50:37.368+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-10-16T16:50:37.388+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:50:37.388+0000] {dag.py:3441} INFO - Setting next_dagrun for weather_etl_pipeline to 2024-10-15T00:00:00+00:00, run_after=2024-10-16T00:00:00+00:00
[2024-10-16T16:50:37.405+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sample.py took 0.089 seconds
[2024-10-16T16:51:07.483+0000] {processor.py:153} INFO - Started process (PID=10655) to work on /opt/airflow/dags/sample.py
[2024-10-16T16:51:07.484+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sample.py for tasks to queue
[2024-10-16T16:51:07.485+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:51:07.484+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sample.py
[2024-10-16T16:51:07.515+0000] {processor.py:753} INFO - DAG(s) dict_keys(['weather_etl_pipeline']) retrieved from /opt/airflow/dags/sample.py
[2024-10-16T16:51:07.531+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:51:07.531+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-10-16T16:51:07.553+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:51:07.552+0000] {dag.py:3441} INFO - Setting next_dagrun for weather_etl_pipeline to 2024-10-15T00:00:00+00:00, run_after=2024-10-16T00:00:00+00:00
[2024-10-16T16:51:07.572+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sample.py took 0.092 seconds
[2024-10-16T16:51:12.903+0000] {processor.py:153} INFO - Started process (PID=10662) to work on /opt/airflow/dags/sample.py
[2024-10-16T16:51:12.904+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sample.py for tasks to queue
[2024-10-16T16:51:12.905+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:51:12.905+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sample.py
[2024-10-16T16:51:12.937+0000] {processor.py:753} INFO - DAG(s) dict_keys(['weather_etl_pipeline']) retrieved from /opt/airflow/dags/sample.py
[2024-10-16T16:51:12.953+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:51:12.953+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-10-16T16:51:12.974+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:51:12.974+0000] {dag.py:3441} INFO - Setting next_dagrun for weather_etl_pipeline to 2024-10-15T00:00:00+00:00, run_after=2024-10-16T00:00:00+00:00
[2024-10-16T16:51:12.992+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sample.py took 0.092 seconds
[2024-10-16T16:52:29.072+0000] {processor.py:153} INFO - Started process (PID=45) to work on /opt/airflow/dags/sample.py
[2024-10-16T16:52:29.073+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/sample.py for tasks to queue
[2024-10-16T16:52:29.073+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:52:29.073+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sample.py
[2024-10-16T16:52:29.151+0000] {processor.py:753} INFO - DAG(s) dict_keys(['weather_etl_pipeline']) retrieved from /opt/airflow/dags/sample.py
[2024-10-16T16:52:29.266+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:52:29.266+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-10-16T16:52:29.311+0000] {logging_mixin.py:137} INFO - [2024-10-16T16:52:29.310+0000] {dag.py:3441} INFO - Setting next_dagrun for weather_etl_pipeline to 2024-10-15T00:00:00+00:00, run_after=2024-10-16T00:00:00+00:00
[2024-10-16T16:52:29.352+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/sample.py took 0.284 seconds
